### ISSUE TITLE
pipe(..., { end: false })

### ISSUE THREAD

**Issue by martinheidegger** [mafintosh/streamx#31]
Shouldn't it be possible to pipe without closing the corresponding write stream [like in node](https://nodejs.org/api/stream.html#stream_readable_pipe_destination_options)?

**Comment by mafintosh** [comment]
I don't know any good use-cases for this, so I decided to gain the simplicity of not having it instead.
If you know any that can't easily be solved by a transform or something like that, I'm super open to it.

**Comment by martinheidegger** [comment]
Hmm, one of the most common usecases is piping to stdout: `Readable.from([1, 2, 3]).pipe(process.stdout, { end: false })`. But it might also be useful to reuse open network streams after a replication has finished in a hypercore-protocol stream?

**Comment by mafintosh** [comment]
Node actually special-cases stdout but i dont think that's a good idea either. Feel free to try a PR on this. If it's a simple addition I'm happy to add it.

**Comment by vweevers** [comment]
Node used to have a special case for that, but not anymore.

**Comment by mafintosh** [comment]
@vweevers https://github.com/nodejs/node/blob/master/lib/internal/streams/readable.js#L657-L659

**Comment by vweevers** [comment]
Ah right, it's different between pipe and pipeline. Wonderful :)

**Comment by mafintosh** [comment]
Streams, the gift that keep on giving 🤣
