### ISSUE TITLE
Duplex.allowHalfOpen

### ISSUE THREAD

**Issue by martinheidegger** [mafintosh/streamx#43]
It seems like the `Duplex` option `allowHalfOpen` is not implemented. Is that on purpose?

**Comment by mafintosh** [comment]
No plans to implement that one, never used it myself. Whats your use-case?

**Comment by martinheidegger** [comment]
Havn't used it either, just trying to be compatible with Node.js streams in https://github.com/mafintosh/utp-native/issues/38

**Comment by mafintosh** [comment]
Ah ok, that one is actually handled internally, if you see the connection code in the 'end' event handler.
