### ISSUE TITLE
Add encoding option but not like readable-stream

### ISSUE THREAD

**Issue by martinheidegger** [mafintosh/streamx#47]
`mapWritable` and `mapReadable` are a neat way to avoid the encoding problem of readable stream but in systems where connections are made between peers usually the encodings are done the same way both ways as in `Object → (encode) → Binary → {Connection - Duplex Stream} → Binary → (decode) → Object` which very much reminds me of [`codecs`](https://www.npmjs.com/package/codecs). It seems like it might be a good idea to have an `encoding` property that takes a codec (aka. Object with `encode` and `decode` function) and uses it instead of `mapWritable`/`mapReadable`. If the `encoding` name is problematic, I could  think that `map` may work well.

**Comment by mafintosh** [comment]
See the PR for my comments
