### ISSUE TITLE
Why no object mode?

### ISSUE THREAD

**Issue by piranna** [mafintosh/streamx#5]
I use it extensively to move objects like in a process pipeline, so they can't be easily mapped to buffers or any other serialization mechanism. In fact, personally I find object streams more powerful than byte stream. What alternative do you propose to use?

**Comment by mafintosh** [comment]
Ah the readme is probably a bit confusing.

Basically in streamx *every* stream behaves as a Node.js object stream. That's what the readme means by object mode being removed.

To mimick Node.js binary stream behaivor you can set two important functions in your constructor, `byteLength` and `map`.

`byteLength` can be used to tell streamx how much memory an object in the stream buffer takes up (just an estimate is fine). This helps it do proper backpressure for buffers/objects/strings/you name it.

The default byteLength function returns the byteLength if buffer or simply 1024, which mimicks how Node.js works with both objectMode and binary streams (ish).

`map` can be used to convert the input/output data into another format. Fx if you are implementing a binary writable stream you might want to map strings to buffers, so you can use the map function to impl that behaviour.

**Comment by piranna** [comment]
So, are all streamx working as object streams by default, not coallecing the buffers but instead using them as `Buffer` objects, and lefting to the user the task to serialize them? That's nice, and the way I think streams should have worked from beginning :-) Yes, definitely you should clarify this in the readme :-)

**Comment by mafintosh** [comment]
Made a quick fix here, https://github.com/mafintosh/streamx/commit/03b0fbd4c3a9131d726c7ddd50d06512303f6e6d

Happy to get more doc contributions also :)

**Comment by piranna** [comment]
> Made a quick fix here, [03b0fbd](https://github.com/mafintosh/streamx/commit/03b0fbd4c3a9131d726c7ddd50d06512303f6e6d)

Much better :-) Thanks! :-D
