### ISSUE TITLE
`streamx.compose` utility?

### ISSUE THREAD

**Issue by phated** [mafintosh/streamx#63]
It seems that nodejs added a [`stream.compose`](https://nodejs.org/dist/latest-v16.x/docs/api/stream.html#streamcomposestreams) utility that is just a [pumpify](https://www.npmjs.com/package/pumpify) equivalent.

Since we use pumpify in glob-stream, it'd be great to just have `streamx.compose` as a utility in this module.

**Comment by phated** [comment]
@mafintosh Any chance you'll be adding this soon? We need it in `vinyl-fs` for the new gulp release.

**Comment by mafintosh** [comment]
Available in stream-composer!
