### ISSUE TITLE
`stream.end()` not propagating as expected

### ISSUE THREAD

**Issue by gmaclennan** [mafintosh/streamx#72]
If I run the following code with `PassThrough` from `node:stream`:

```js
import { PassThrough } from 'node:stream'

const s1 = new PassThrough()
const s2 = new PassThrough()

s1.on('end', () => console.log('s1 end'))
s1.on('close', () => console.log('s1 close'))
s1.on('error', () => console.log('s1 error'))

s2.on('end', () => console.log('s2 end'))
s2.on('close', () => console.log('s2 close'))
s2.on('error', () => console.log('s2 error'))

s1.pipe(s2).pipe(s1)

s1.end()
```

Then what is logged is:

```
s1 end
s2 end
s1 close
s2 close
```

This is what I would expect. If I run the same code with `import { Passthrough } from 'streamx'` then I get the following:

```
s1 end
s1 close
s2 error
s2 close
```
Where the error is:
```
Error: Writable stream closed prematurely
    at Pipeline.done (node_modules/streamx/index.js:402:43)
    at ReadableState.afterDestroy (node_modules/streamx/index.js:457:56)
    at PassThrough._destroy (node_modules/streamx/index.js:542:5)
    at ReadableState.updateNonPrimary (node_modules/streamx/index.js:355:16)
    at ReadableState.update (node_modules/streamx/index.js:339:69)
    at ReadableState.updateReadNT (node_modules/streamx/index.js:484:8)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

I get the same result on both node `v16.20.0` and node `v18.16.0`.

This is relevant because I am trying to debug unexpected stream ending behaviour with Hypercore https://github.com/holepunchto/hypercore/issues/366

**Comment by gmaclennan** [comment]
Using `streamx@2.13.2`

**Comment by mafintosh** [comment]
Would say this is a node bug, or undefined behaivour. You are ending the stream you are piping to manually, so anything that is "stuck" in the pipeline, `s2` here, will be written to the stream you just ended later, ie premature close.
