### ISSUE TITLE
Problem merging streams

### ISSUE THREAD

**Issue by gtbuchanan** [mafintosh/streamx#85]
I recently upgraded to Gulp 5 but ran into an issue with one of our tasks utilizing [`streamqueue`](https://github.com/nfroidure/StreamQueue) to merge/concatenate streams in order. Here is an example:

```javascript
const src1 = src('source1.js'); // In real code, each of these sources might have different transformations
const src2 = src('source2.js');

return streamqueue({ objectMode: true }, src1, src2)
    .pipe(concat('source.js')) // gulp-concat
    .pipe(dest('dist'));
```

This fails with the following error:

```
Error: write after end
    at writeAfterEnd (**redacted**\node_modules\.pnpm\readable-stream@2.3.7\node_modules\readable-stream\lib\_stream_writable.js:288:12)
    at Writable.write (**redacted**\node_modules\.pnpm\readable-stream@2.3.7\node_modules\readable-stream\lib\_stream_writable.js:332:20)
    at ReadableState.drain (**redacted**\node_modules\.pnpm\streamx@2.16.1\node_modules\streamx\index.js:343:47)
    at ReadableState.update (**redacted**\node_modules\.pnpm\streamx@2.16.1\node_modules\streamx\index.js:354:12)
    at ReadableState.updateReadNT (**redacted**\node_modules\.pnpm\streamx@2.16.1\node_modules\streamx\index.js:536:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

Obviously, I understand that you do not maintain `streamqueue` and it is fairly old. However, is there something built-in to `streamx` that I can use to accomplish the same thing (or perhaps another library I'm missing)?

I took a look at `stream-composer` because it sounded like what I needed, but it doesn't seem to fit the same use case exactly.

**Comment by phated** [comment]
@gtbuchanan have you tried https://github.com/gulpjs/ordered-read-streams

I rewrote it to support streamx. The docs are pretty lacking, but the usage should be relatively the same as `streamqueue`.

**Comment by gtbuchanan** [comment]
@phated No, I totally missed that one! Thank you! I replaced `streamqueue` with `ordered-read-streams`, but now I'm receiving the error "All input streams must be readable". I suspect this is because we're using the deprecated [`gulp-angular-templatecache`](https://github.com/miickel/gulp-angular-templatecache) that is based on an older version of Gulp. After piping to it, `typeof stream.read` evaluates to `undefined` for the resulting stream.

I guess we'll have to figure out another way forward for that library, but at least we now have a replacement for `streamqueue`. Thanks again!

**Comment by gtbuchanan** [comment]
For anybody stumbling across this with the same problem, I was able to fix `gulp-angular-templatecache` by replacing `map-stream` with `streamx` and replacing `stream-combiner` with `stream-composer`:

https://github.com/energyworldnet/gulp-angular-templatecache/commit/dc3a1d2e2d77c11191a999675eadb7bb879ee214
