### ISSUE TITLE
Better error handling in pipes

### ISSUE THREAD

**Issue by ehmicky** [mafintosh/streamx#93]
When piping streams, `streamx` adds an `error` listener. This `error` listener is not cleaned up when the pipe ends (including due to an error).

https://github.com/mafintosh/streamx/blob/625ce37f624aa51cda95fa1bffdc3fae2ecd03a5/index.js#L274

This is unlike Node.js streams, which do clean up any listener added by `.pipe()`:

https://github.com/nodejs/readable-stream/blob/c85db76d4c41f64fd082c9263c3a918bec6f38a0/lib/_stream_readable.js#L639

This bug ends up creating some bigger problem with Gulp, explained here: https://github.com/gulpjs/gulp/issues/2812

**Comment by mafintosh** [comment]
Feel free to open a pr that removes it after the stream has been fully torn down

**Comment by ehmicky** [comment]
Hi @mafintosh,

It turns out the problem was slightly different. I opened #94 with the actual issue.
